# Generated by Django 5.0.4 on 2024-09-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True, default="default_profile.jpg", null=True, upload_to="img/"
            ),
        ),
    ]
