# Generated by Django 5.0.4 on 2024-09-13 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="event_participations",
            field=models.ManyToManyField(through="app.Participation", to="app.event"),
        ),
        migrations.AlterField(
            model_name="participation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="default_profile.jpg",
                null=True,
                upload_to="app/img/",
            ),
        ),
    ]
