# Generated by Django 5.0.4 on 2024-10-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_alter_user_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=9),
        ),
    ]
