# Generated by Django 5.0.4 on 2024-10-07 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_event_latitude_event_longitude"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subcomment",
            name="parent_comment",
        ),
        migrations.RemoveField(
            model_name="subcomment",
            name="user",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
        migrations.DeleteModel(
            name="SubComment",
        ),
    ]
