# Generated by Django 5.0.4 on 2024-10-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_subcomment_parent_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="static/app/img/default_profile.jpg",
                null=True,
                upload_to="static/app/img/",
            ),
        ),
    ]
